# Generated by Django 4.2.2 on 2023-08-05 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notifications', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('real_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('slogan', models.CharField(max_length=20)),
                ('introduction', models.TextField()),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.image')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.IntegerField()),
                ('workspace_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('is_personal', models.BooleanField()),
                ('members', models.ManyToManyField(related_name='joined_workspaces', to='database.user')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.image')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('belong_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.activity')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20)),
                ('belong_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='database.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20)),
                ('belong_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='MissionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('IP', 'in progress'), ('P', 'pending'), ('C', 'close')], default='IP', max_length=2)),
                ('name', models.CharField(max_length=20)),
                ('belong_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='belong_workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.workspace'),
        ),
        migrations.AddField(
            model_name='activity',
            name='childs',
            field=models.ManyToManyField(blank=True, related_name='parents', to='database.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contributors',
            field=models.ManyToManyField(related_name='contributing_activities', to='database.user'),
        ),
        migrations.AddField(
            model_name='activity',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('belong_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.activity')),
                ('deadline', models.DateTimeField()),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.missionstate')),
            ],
        ),
    ]
