# Generated by Django 4.2.2 on 2023-08-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='description',
            field=models.TextField(),
        ),
    ]
