# Generated by Django 4.2.2 on 2023-07-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_user_groups_user_is_staff_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
