# Generated by Django 4.2.2 on 2023-08-12 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_workspace_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='notifications',
        ),
        migrations.AlterField(
            model_name='missionstate',
            name='stage',
            field=models.CharField(choices=[('IN_PROGRESS', 'in progress'), ('PENDING', 'pending'), ('CLOSE', 'close')], default='IN_PROGRESS', max_length=15),
        ),
        migrations.CreateModel(
            name='ActivityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_time', models.DateTimeField()),
                ('belong_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='database.activity')),
            ],
        ),
    ]
